export const characters = [
  {
    id: 1,
    name: "Harry Potter",
    house: "Gryffindor",
    img_house: "https://i.ibb.co/Gcx316n/Gryffindor.png",
    description:
      "Harry Potter, o órfão com uma cicatriz em forma de raio na testa, descobre que é um bruxo e entra em um mundo mágico sombrio e enigmático. Com seus amigos, ele enfrenta desafios, descobre segredos e luta contra as trevas para proteger aqueles que ama.",
    img_path: "harry_potter.png",
    blood: "Meio-sangue",
    patronus: "Veado",
  },
  {
    id: 2,
    name: "Hermione Granger",
    house: "Gryffindor",
    img_house: "https://i.ibb.co/Gcx316n/Gryffindor.png",
    description:
      "Hermione Granger, a bruxinha nascida trouxa com uma sede insaciável por conhecimento oculto e misterioso. Com sua coragem e inteligência, ela apoia Harry e Rony em suas jornadas na escuridão do mundo bruxo.",
    img_path: "hermione_granger.png",
    blood: "Nascida trouxa",
    patronus: "Lontra",
  },
  {
    id: 3,
    name: "Rony Weasley",
    house: "Gryffindor",
    img_house: "https://i.ibb.co/Gcx316n/Gryffindor.png",
    description:
      "Rony Weasley, amigo leal e atrapalhado, enfrenta desafios assustadores ao lado de Harry e Hermione. Ele demonstra bravura e lealdade inabaláveis, trazendo luz e humor para as sombras sombrias.",
    img_path: "rony_weasley.png",
    blood: "Sangue puro",
    patronus: "Jack Russell Terrier",
  },
  {
    id: 4,
    name: "Draco Malfoy",
    house: "Slytherin",
    img_house: "https://i.ibb.co/dW24M4V/Slytherin.png",
    description:
      "Draco Malfoy, herdeiro de uma linhagem sombria e arrogante, é atormentado por escolhas difíceis em um mundo gótico e sinistro. Sua busca por poder o coloca em confronto com Harry, Hermione e Rony.",
    img_path: "draco_malfoy.png",
    blood: "Sangue puro",
    patronus: "Falcão-real",
  },
  {
    id: 5,
    name: "Gina Weasley",
    house: "Gryffindor",
    img_house: "https://i.ibb.co/Gcx316n/Gryffindor.png",
    description:
      "Gina Weasley, garota valente e encantadora, se destaca nas sombras do mundo bruxo. Com seu espírito destemido, ela enfrenta desafios e combate as trevas ao lado dos amigos.",
    img_path: "gina_weasley.png",
    blood: "Sangue puro",
    patronus: "Cavalo",
  },
  {
    id: 6,
    name: "Luna Lovegood",
    house: "Ravenclaw",
    img_house: "https://i.ibb.co/NstbPd6/Ravenclaw.png",
    description:
      "Luna Lovegood, uma alma peculiar e sensível, enxerga além da escuridão para ver as maravilhas do mundo invisível. Com sua perspectiva única, ela traz esperança e mistério para o universo sombrio de Tim Burton.",
    img_path: "luna_lovegood.png",
    blood: "Sangue puro",
    patronus: "Lebre",
  },
  {
    id: 7,
    name: "Fred e Jorge Weasley",
    house: "Gryffindor",
    img_house: "https://i.ibb.co/Gcx316n/Gryffindor.png",
    description:
      "Fred e Jorge Weasley, gêmeos travessos e hilariantes, levam sua comédia e malabarismo ao mundo sombrio e enigmático de Tim Burton. Eles espalham risos e caos, mesmo em tempos de trevas.",
    img_path: "fred_jorge_weasley.png",
    blood: "Sangue puro",
    patronus: "Coruja",
  },
  {
    id: 8,
    name: "Neville Longbottom",
    house: "Gryffindor",
    img_house: "https://i.ibb.co/Gcx316n/Gryffindor.png",
    description:
      "Neville Longbottom, um jovem bruxo tímido e corajoso, supera suas inseguranças para enfrentar as sombras e proteger seus amigos. Ele cresce e floresce no mundo macabro de Tim Burton.",
    img_path: "neville_longbottom.png",
    blood: "Sangue puro",
    patronus: "Cachorro-vinagre",
  },
  {
    id: 9,
    name: "Dobby",
    house: "Free Elf",
    img_house: "https://i.ibb.co/Tc9LV0C/hogwarts-logo-removebg-preview.png",
    description:
      "Dobby, um elfo doméstico leal e livre, foge das sombras opressoras para encontrar sua liberdade no mundo peculiar de Tim Burton. Sua dedicação e sacrifício são marcados por uma aura mágica sombria.",
    img_path: "dobby.png",
    blood: "Nascido trouxa",
    patronus: "Não possui patrono",
  },
  {
    id: 10,
    name: "Albus Dumbledore",
    house: "Gryffindor",
    img_house: "https://i.ibb.co/Gcx316n/Gryffindor.png",
    description:
      "Albus Dumbledore, o mago sábio e enigmático, carrega segredos profundos em seu coração ao atravessar o mundo sombrio e intrigante de Tim Burton. Sua sabedoria guia Harry Potter em sua jornada.",
    img_path: "albus_dumbledore.png",
    blood: "Sangue puro",
    patronus: "Fênix",
  },
  {
    id: 11,
    name: "Minerva McGonagall",
    house: "Gryffindor",
    img_house: "https://i.ibb.co/Gcx316n/Gryffindor.png",
    description:
      "Minerva McGonagall, professora rígida e nobre, esconde uma magia misteriosa por trás de sua aparência austera no mundo gótico de Tim Burton. Seu olhar vigilante protege Hogwarts em tempos de trevas.",
    img_path: "minerva_mcgonagall.png",
    blood: "Sangue puro",
    patronus: "Gato",
  },
  {
    id: 12,
    name: "Severo Snape",
    house: "Slytherin",
    img_house: "https://i.ibb.co/dW24M4V/Slytherin.png",
    description:
      "Severo Snape, um poção de amor e ódio, navega entre a luz e a escuridão em um mundo sombrio e enigmático. Suas motivações ocultas são reveladas na jornada de Harry Potter.",
    img_path: "severo_snape.png",
    blood: "Meio-sangue",
    patronus: "Cervo",
  },
  {
    id: 19,
    name: "Lúcio Malfoy",
    house: "Slytherin",
    img_house: "https://i.ibb.co/dW24M4V/Slytherin.png",
    description:
      "Lúcio Malfoy, comandante influente, tece intrigas e espalha sua influência sinistra no mundo das sombras sombrias de Tim Burton. Seu desejo por poder molda o destino de muitos.",
    img_path: "lucio_malfoy.png",
    blood: "Sangue puro",
    patronus: "Furão",
  },
  {
    id: 14,
    name: "Sirius Black",
    house: "Gryffindor",
    img_house: "https://i.ibb.co/Gcx316n/Gryffindor.png",
    description:
      "Sirius Black, um prisioneiro inocente encarcerado em Azkaban, exala uma aura sombria e misteriosa no mundo enigmático de Tim Burton. Seu desejo de liberdade impulsiona a história.",
    img_path: "sirius_black.png",
    blood: "Sangue puro",
    patronus: "Cervo",
  },
  {
    id: 15,
    name: "Lord Voldemort",
    house: "Slytherin",
    img_house: "https://i.ibb.co/dW24M4V/Slytherin.png",
    description:
      "Lord Voldemort, a personificação das trevas e do medo, espalha terror e caos no mundo mágico de Tim Burton. Sua busca implacável pela dominação e imortalidade o torna o principal antagonista da saga.",
    img_path: "lord_voldemort.png",
    blood: "Sangue puro",
    patronus: "Não possui patrono",
  },
  {
    id: 16,
    name: "Tom Riddle / Lord Voldemort",
    house: "Slytherin",
    img_house: "https://i.ibb.co/dW24M4V/Slytherin.png",
    description:
      "Tom Riddle, o jovem bruxo ambicioso e sinistro, mergulha nas artes das trevas no universo sombrio de Tim Burton. Conforme se torna Lord Voldemort, seu poder sombrio e busca por imortalidade ameaçam o mundo bruxo.",
    img_path: "tom_riddle.png",
    blood: "Sangue puro",
    patronus: "Não possui patrono",
  },
  {
    id: 17,
    name: "Bellatrix Lestrange",
    house: "Slytherin",
    img_house: "https://i.ibb.co/dW24M4V/Slytherin.png",
    description:
      "Bellatrix Lestrange, uma seguidora fiel e insana de Lord Voldemort, espalha caos e terror com sua personalidade sombria e fanática em um mundo gótico macabro.",
    img_path: "bellatrix_lestrange.png",
    blood: "Sangue puro",
    patronus: "Não possui patrono",
  },
  {
    id: 18,
    name: "Dolores Umbridge",
    house: "Slytherin",
    img_house: "https://i.ibb.co/dW24M4V/Slytherin.png",
    description:
      "Dolores Umbridge, uma autoridade tirânica com aparência doce e terrível, semeia o terror em Hogwarts no mundo sombrio e peculiar de Tim Burton.",
    img_path: "dolores_umbridge.png",
    blood: "Sangue puro",
    patronus: "Gato",
  },
];
